import React from 'react';
import BlogCard from './components/BlogCard'; // Adjust the import path as needed
import { Link } from 'react-router-dom';
import Overall from './images/Overall.jpg';

const BlogList = () => {
    const blogs = [
        {
            title: 'Filament Recycler Under 100 Dollars',
            description: 'An Open Source solution to the waste generated by your printer',
            date: 'Oct 16, 2024',
            preview: '3D printing enthusiasts often face the issue of filament waste, which not only impacts the environment but also adds ...',
            imageUrl: Overall,
            url: 'Filament-Recycler'
        },
      
    ];

    return (
        <div style={{
            display: 'flex',
            flexWrap: 'wrap', // Allows the cards to wrap into the next row
            justifyContent: 'center', // Centers the cards in the row
            gap: '2.5em', // Provides spacing between the cards
            padding: '2em',
            backgroundColor: '#f9f9f9',
            minHeight: '100vh',
            width: '100%',
            alignContent:'flex-start'
        }}>
            <h1 style={{ 
                width: '100%', // Ensure the title takes the full width of the container
                textAlign: 'center', 
                fontSize: '2.5em', 
                marginBottom: '1.5em', 
                color: '#333' ,
                marginTop:'1em'
            }}>
                Our Blog
            </h1>
            {blogs.map((blog, index) => (
                <Link to={`/blogs/${blog.url}`}>
                <BlogCard
                    key={index}
                    title={blog.title}
                    description={blog.description}
                    date={blog.date}
                    preview={blog.preview}
                    imageUrl={blog.imageUrl}
                />
                </Link>
            ))}
        </div>
    );
};

export default BlogList;
